name: fitpil
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  sqflite: ^2.2.0
  path: ^1.8.3
  path_provider: ^2.0.11
  pedometer: ^4.0.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.4.3
  intl: ^0.18.0
  video_player: ^2.9.2
  provider: ^6.1.2
  fl_chart: ^0.69.2
  permission_handler: ^11.3.1
  http: ^1.2.2
  keyboard_avoider: ^0.2.0
  flutter_dotenv: ^5.2.1
  flutter_html: ^3.0.0-beta.2
  flutter_colorpicker: ^1.1.0
  icons_plus: ^5.0.0
  url_launcher: ^6.3.1
  flutter_html_table: ^3.0.0-beta.2
  syncfusion_flutter_charts: ^27.2.5
  google_nav_bar: ^5.0.7

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/maskot1.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

  assets:
    - images/
    - .env

  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "images/maskot1.png"
